[package]
name = "get_clip_img"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.1"
base64 = "0.13.0"
webbrowser = "0.6.0"
soloud = "1.0.2"
clipboard-win = "4.4.2"
reqwest = {version="0.11.13",features=["blocking","json"]}
serde_json = "1.0.89"